@extends('layout.admid_layout')

@section('content')
<div class="box box-warning marginl">

                @include('category/indi1-1show',['c','count','nameteacher'
                  ,'educ_bg','y','checkpass','checknotpass','tc_course','instructor','specialinstructor','inc','course'])
</div>
<style>
.marginl{
  padding:10px;
}
.wid10{
  width:10%;
}
.wid20{
  width:20%;
}
.wid30{
  width:30%;
}
.wid40{
  width:40%;
}
.wid50{
  width:50%;
}
.mt20{
  margin-top:50px
}
.ml-1{
  margin-left:10px
}
.ml-2{
  margin-left:20px
}
.mt-3{
  margin-top:30px;
}
</style>
@endsection